apiVersion : apps/v1
kind: Deployment
metadata:
  name: "steveteam11aks-6fd3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "steveteam11aks-6fd3"
  template:
    metadata:
      labels:
        app: "steveteam11aks-6fd3"
    spec:
      containers:
        - name: "steveteam11aks-6fd3"
          image: "registrybwj5358.azurecr.io/steveteam11aks"
          ports:
          - containerPort: 80