apiVersion: v1
kind: Service
metadata:
    name: "steveteam11aks-6fd3"
    labels:
        app: "steveteam11aks-6fd3"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "steveteam11aks-6fd3"